# Generated by Django 5.0.3 on 2024-03-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='good_student',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='locker_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
